LPTest2/LPTest2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sites.urls'))
]

LPTest2/sites/urls.py
from django.conf.urls import url
from . import views

app_name = 'sites'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<lob>.*)/(?P<site_id>[0-9]+)/$', views.site, name='site'),
    url(r'^add_site$', views.add_site, name='add_site'),
    url(r'^site_added$', views.site_added, name='site_added')
]

LPTest2/sites/models.py
from __future__ import unicode_literals

from django.db import models


class Version(models.Model):
    name = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.name


class Lob(models.Model):
    name = models.CharField(max_length=10, unique=True)
    location = models.CharField(max_length=100)

    def __str__(self):
        return '{0}  [{1}]'.format(self.name, self.location)


class Site(models.Model):
    id = models.CharField(primary_key=True, max_length=20, unique=True)
    lob = models.ForeignKey(Lob, on_delete=models.CASCADE)
    version = models.ForeignKey(Version, on_delete=models.CASCADE)
    comments = models.CharField(max_length=100, blank=True)
    date_added = models.DateTimeField('date_added', auto_now_add=True)

    def __str__(self):
        if self.comments:
            return '{0} - {1}, {2} ({3})'.format(self.id, self.lob, self.version, self.comments)
        else:
            return '{0} - {1}, {2}'.format(self.id, self.lob, self.version)

LPTest2/sites/forms.py
from django.forms import ModelForm
from .models import Site


class SiteForm(ModelForm):
    class Meta:
        model = Site
        fields = '__all__'

LPTest2/sites/views.py
from django.shortcuts import render
from time import strftime
from .models import Lob, Site, Version
from .forms import SiteForm


def home(request):
    return render(request, "home.html", {'date': strftime("%A, %B %d %Y"),
                                         'lobs': Lob.objects.all(),
                                         'sites': Site.objects.all(),
                                         'versions': Version.objects.all(),
                                         'show_add_site': True})


def site(request, lob, site_id):
    site_arg = Site.objects.filter(id=site_id)
    if str(site_arg.first().lob.name) == 'ALPHA':
        return render(request, "site_ALPHA.html",
                      {'date': strftime("%A, %B %d %Y"),
                       'site': site_id,
                       'title': '{0} {1} Site - {2}'.format(lob, 'ALPHA', site_id),
                       'lobs': Lob.objects.all(),
                       'sites': Site.objects.all(),
                       'versions': Version.objects.all(),
                       'show_add_site': True})

    version = str(site_arg.first().version)
    return render(request, "site_%s.html" % version,
                  {'date': strftime("%A, %B %d %Y"),
                   'site': site_id,
                   'title': '{0} {1} Site - {2}'.format(lob, version, site_id),
                   'lobs': Lob.objects.all(),
                   'sites': Site.objects.all(),
                   'versions': Version.objects.all(),
                   'show_add_site': True})


def add_site(request):
    if request.method == 'POST':
        form = SiteForm(data=request.POST)
        if form.is_valid():
            form.save()
            return render(request, "site_added.html", {'show_add_site': False})
    else:
        form = SiteForm()
        return render(request, "add_site.html", {'form': form})


def site_added(request):
    return render(request, "site_added.html", {'show_add_site': True})

LPTest2/sites/templates/add_site.html
{% extends "base.html" %}
{% block title %}
<title>Add Site - LivePerson Test Sites</title>
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div>
            <div style="text-decoration: underline">Add site</div>
            {% for field in form %}
                <div>
                {% if field.name == "id" or field.name == "lob" %}
                    {{ field.name|upper }} {{field}}
                {% else %}
                    {{ field.name|title }} {{field}}
                {% endif %}
                </div>
            {% endfor %}
            <input type="submit" value="Save"/>
        </div>
    </form>
{% endblock%}

LPTest2/sites/templates/base.html
{% load staticfiles%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'styles.css' %}"/>
        {% block javascript %}
        {% endblock %}
        {% block title %}
        {% endblock %}
    </head>
    <body>
        <header>
            <h1>LivePerson Test Sites</h1>
        </header>
        <nav>
            <div class="dropdown">
                <button class="dropbtn" onclick="location.href='/'">HOME</button>
            </div>
            {% for lob in lobs %}
            <div class="dropdown">
                <button class="dropbtn">{{ lob.name }}</button>
                <div class="dropdown-content">
                    {% for site in sites %}
                    {% ifequal site.lob lob %}
                    <a href="{% url 'sites:site' lob.name site.id %}">{{ site.id }} ({{ site.version}}) {{ site.comments }}</a>
                    {% endifequal %}
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </nav>
        <section>
            <p>
                {% if date %}
                    {{ date }}<br/><br/>
                {% endif %}
                {% block content %}
                {% endblock %}
            </p>
        </section>
        {% if show_add_site %}
        <div class="add_site_link">
            <a href="/add_site">Add Site</a>
        </div>
        {% endif %}
        <footer>
            ---------------------------------------------------------------------
            <div id="copyright">&copy; 2016 Moshe Shitrit. All rights reserved.</div>
        </footer>
    </body>
</html>

LPTest2/sites/templates/home.html
{% extends "base.html" %}
{% block title %}
<title>Home - LivePerson Test Sites</title>
{% endblock %}
{% block content %}
        This website has dedicated pages for all of my test sites in LivePerson
{% endblock%}

LPTest2/sites/templates/site_ALPHA.html
{% extends "base.html" %}
{% block title %}
<title>{{ title }} - LivePerson Test Sites</title>
{% endblock %}
{% block javascript %}
    <!-- BEGIN LivePerson Monitor. -->
    <script type="text/javascript"> window.lpTag=window.lpTag||{};if(typeof window.lpTag._tagCount==='undefined'){window.lpTag={site:'{{ site }}'||'',section:lpTag.section||'',autoStart:lpTag.autoStart===false?false:true,ovr:lpTag.ovr||{domain : 'lptag-a.liveperson.net',tagjs : 'tags-a.liveperson.net'},_v:'1.6.0',_tagCount:1,protocol:'https:',events:{bind:function(app,ev,fn){lpTag.defer(function(){lpTag.events.bind(app,ev,fn);},0);},trigger:function(app,ev,json){lpTag.defer(function(){lpTag.events.trigger(app,ev,json);},1);}},defer:function(fn,fnType){if(fnType==0){this._defB=this._defB||[];this._defB.push(fn);}else if(fnType==1){this._defT=this._defT||[];this._defT.push(fn);}else{this._defL=this._defL||[];this._defL.push(fn);}},load:function(src,chr,id){var t=this;setTimeout(function(){t._load(src,chr,id);},0);},_load:function(src,chr,id){var url=src;if(!src){url=this.protocol+'//'+((this.ovr&&this.ovr.domain)?this.ovr.domain:'lptag.liveperson.net')+'/tag/tag.js?site='+this.site;}var s=document.createElement('script');s.setAttribute('charset',chr?chr:'UTF-8');if(id){s.setAttribute('id',id);}s.setAttribute('src',url);document.getElementsByTagName('head').item(0).appendChild(s);},init:function(){this._timing=this._timing||{};this._timing.start=(new Date()).getTime();var that=this;if(window.attachEvent){window.attachEvent('onload',function(){that._domReady('domReady');});}else{window.addEventListener('DOMContentLoaded',function(){that._domReady('contReady');},false);window.addEventListener('load',function(){that._domReady('domReady');},false);}if(typeof(window._lptStop)=='undefined'){this.load();}},start:function(){this.autoStart=true;},_domReady:function(n){if(!this.isDom){this.isDom=true;this.events.trigger('LPT','DOM_READY',{t:n});}this._timing[n]=(new Date()).getTime();},vars:lpTag.vars||[],dbs:lpTag.dbs||[],ctn:lpTag.ctn||[],sdes:lpTag.sdes||[],ev:lpTag.ev||[]};lpTag.init();}else{window.lpTag._tagCount+=1;} </script>
    <!-- END LivePerson Monitor. -->
{% endblock %}
{% block content %}
    {{ title }}
{% endblock %}

LPTest2/sites/templates/site_Legacy.html
{% extends "base.html" %}
{% block title %}
<title>{{ title }} - LivePerson Test Sites</title>
{% endblock %}
{% block javascript %}
    <!-- BEGIN LivePerson Monitor. -->
    <script type="text/javascript">
        window.lpTag=window.lpTag||{};if(typeof window.lpTag._tagCount==='undefined'){window.lpTag={site:'{{ site }}',section:lpTag.section||'',autoStart:lpTag.autoStart===false?false:true,ovr:lpTag.ovr||{},_v:'1.5.1',_tagCount:1,protocol:location.protocol,events:{bind:function(app,ev,fn){lpTag.defer(function(){lpTag.events.bind(app,ev,fn)},0)},trigger:function(app,ev,json){lpTag.defer(function(){lpTag.events.trigger(app,ev,json)},1)}},defer:function(fn,fnType){if(fnType==0){this._defB=this._defB||[];this._defB.push(fn)}else if(fnType==1){this._defT=this._defT||[];this._defT.push(fn)}else{this._defL=this._defL||[];this._defL.push(fn)}},load:function(src,chr,id){var t=this;setTimeout(function(){t._load(src,chr,id)},0)},_load:function(src,chr,id){var url=src;if(!src){url=this.protocol+'//'+((this.ovr&&this.ovr.domain)?this.ovr.domain:'lptag.liveperson.net')+'/tag/tag.js?site='+this.site}var s=document.createElement('script');s.setAttribute('charset',chr?chr:'UTF-8');if(id){s.setAttribute('id',id)}s.setAttribute('src',url);document.getElementsByTagName('head').item(0).appendChild(s)},init:function(){this._timing=this._timing||{};this._timing.start=(new Date()).getTime();var that=this;if(window.attachEvent){window.attachEvent('onload',function(){that._domReady('domReady')})}else{window.addEventListener('DOMContentLoaded',function(){that._domReady('contReady')},false);window.addEventListener('load',function(){that._domReady('domReady')},false)}if(typeof(window._lptStop)=='undefined'){this.load()}},start:function(){this.autoStart=true},_domReady:function(n){if(!this.isDom){this.isDom=true;this.events.trigger('LPT','DOM_READY',{t:n})}this._timing[n]=(new Date()).getTime()},vars:lpTag.vars||[],dbs:lpTag.dbs||[],ctn:lpTag.ctn||[],sdes:lpTag.sdes||[],ev:lpTag.ev||[]};lpTag.init()}else{window.lpTag._tagCount+=1}
    </script>
    <!-- END LivePerson Monitor. -->
{% endblock %}
{% block content %}
    {{ title }}
{% endblock %}

LPTest2/sites/templates/site_LiveEngage2.html
{% extends "base.html" %}
{% block title %}
<title>{{ title }} - LivePerson Test Sites</title>
{% endblock %}
{% block javascript %}
    <!-- BEGIN LivePerson Monitor. -->
    <script type="text/javascript"> window.lpTag=window.lpTag||{};if(typeof window.lpTag._tagCount==='undefined'){window.lpTag={site:'{{ site }}'||'',section:lpTag.section||'',autoStart:lpTag.autoStart===false?false:true,ovr:lpTag.ovr||{},_v:'1.6.0',_tagCount:1,protocol:'https:',events:{bind:function(app,ev,fn){lpTag.defer(function(){lpTag.events.bind(app,ev,fn);},0);},trigger:function(app,ev,json){lpTag.defer(function(){lpTag.events.trigger(app,ev,json);},1);}},defer:function(fn,fnType){if(fnType==0){this._defB=this._defB||[];this._defB.push(fn);}else if(fnType==1){this._defT=this._defT||[];this._defT.push(fn);}else{this._defL=this._defL||[];this._defL.push(fn);}},load:function(src,chr,id){var t=this;setTimeout(function(){t._load(src,chr,id);},0);},_load:function(src,chr,id){var url=src;if(!src){url=this.protocol+'//'+((this.ovr&&this.ovr.domain)?this.ovr.domain:'lptag.liveperson.net')+'/tag/tag.js?site='+this.site;}var s=document.createElement('script');s.setAttribute('charset',chr?chr:'UTF-8');if(id){s.setAttribute('id',id);}s.setAttribute('src',url);document.getElementsByTagName('head').item(0).appendChild(s);},init:function(){this._timing=this._timing||{};this._timing.start=(new Date()).getTime();var that=this;if(window.attachEvent){window.attachEvent('onload',function(){that._domReady('domReady');});}else{window.addEventListener('DOMContentLoaded',function(){that._domReady('contReady');},false);window.addEventListener('load',function(){that._domReady('domReady');},false);}if(typeof(window._lptStop)=='undefined'){this.load();}},start:function(){this.autoStart=true;},_domReady:function(n){if(!this.isDom){this.isDom=true;this.events.trigger('LPT','DOM_READY',{t:n});}this._timing[n]=(new Date()).getTime();},vars:lpTag.vars||[],dbs:lpTag.dbs||[],ctn:lpTag.ctn||[],sdes:lpTag.sdes||[],ev:lpTag.ev||[]};lpTag.init();}else{window.lpTag._tagCount+=1;} </script>
    <!-- END LivePerson Monitor. -->
{% endblock %}
{% block content %}
    {{ title }}
{% endblock %}

LPTest2/sites/templates/site_added.html
{% extends "base.html" %}
{% block title %}
<title>Success!</title>
{% endblock %}
{% block content %}
    Site added successfully!
{% endblock%}